### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by alexbogo** [automatephp/automate#29]
Hi,

I know this is not an issue, but couldn't find better place to ask.
From docs, if deployment is not successful, for any reason, e.g. syntax error in config file or permissions on remote server, any error...  it will auto preserve previous deployment version, there is no need to execute "rollback" command? 

Thanks

**Comment by julienj** [comment]
Hello.  
Yes, the new version is not deployed in case of error.  Except for errors in the post_deploy hock

**Comment by alexbogo** [comment]
Hi,

Thank you for the clarification.
