### ISSUE TITLE
ED25519 keys not supported

### ISSUE THREAD

**Issue by foxycode** [automatephp/automate#33]
Took me some time to figure it out, only error I saw was:
`[ERROR] [server] SSH key or passphrase is invalid`

After changing key to RSA, it works.

**Comment by julienj** [comment]
actually only rsa is supported

it should not be too complex to add other algo :
https://github.com/automatephp/automate/blob/master/src/Automate/SessionFactory.php

Contributions are welcome :)

**Comment by foxycode** [comment]
Will look into it :)
