### ISSUE TITLE
Error when deploy server is not in known_hosts

### ISSUE THREAD

**Issue by foxycode** [automatephp/automate#34]
I've got only not much descriptive error:
`[ERROR] Host key verification failed.`

After some research, I found that Automate can't handle unknown SSH hosts (not present in `~/.ssh/known_hosts` file. I needed to add to deploy trigger these:
```bash
mkdir ~/.ssh
chmod 700 ~/.ssh
ssh-keyscan -t rsa server > ~/.ssh/known_hosts
```

I believe this should be Automate's work.

**Comment by julienj** [comment]
Hello,

You have this error when connecting to the target server from your computer
or for connection form target server to the git server ?

**Comment by foxycode** [comment]
Reason for this error is running from CI Docker container. On my machine, I have target server in hosts. But I need to connect from CI server, which always runs new Ubuntu 18.04 container.

**Comment by julienj** [comment]
I already had this problem
I use the CI pipeline to add the key in this case (before call Automate)

I think Automate should not modify the ssh configuration itself

**Comment by foxycode** [comment]
@julienj What about adding option for SSH fingeprint? THis way I could define it in config. I can try to send PR if you are ok with it.

**Comment by julienj** [comment]
with pleasure
