### ISSUE TITLE
Gitlab Variable is not access as ssh password or ssh_key

### ISSUE THREAD

**Issue by PeanutSquareLLP** [automatephp/automate#41]

**Comment by julienj** [comment]
Hello,

Can you give more details? 
We use automate with Gitlab on many projects without issue.

Some information to help you:

- You must prefix the variable with "AUTOMATE__" in Gitlab (Settings > CI/CD > Variables)
- if your branch is "Protected" you must put the variable as "Protected"

exemple :

![image](https://user-images.githubusercontent.com/193469/157750025-52109414-054f-497a-b833-3a517aca7536.png)

**Comment by PeanutSquareLLP** [comment]
it works thanks @julienj
