### ISSUE TITLE
Vendor folder as a symlink

### ISSUE THREAD

**Issue by alexbogo** [automatephp/automate#46]
Hi, 

With Symfony version 4.* this worked perfectly, I had the vendor folder in the shared folder set up, so there was no need for "composer install" every time on deployment... 
Running "assets:install --symlink" in post_deploy,  worked perfectly.

After upgrading to Symfony 5, this is not working anymore... Symfony command complains that it can't find the .env file in the "shared" folder but it should look into the "current/vendor" folder.

Is this something that can be fixed? 

Thanks
Alex

**Comment by julienj** [comment]
Hello Alex

Thank you for reaching out. As this ticket is old, we're closing it now. However, if you need further assistance, feel free to reach out. We've recently resumed development with the release of version 4.0.0-beta1.
