### ISSUE TITLE
Why not Deployer?

### ISSUE THREAD

**Issue by antonmedv** [automatephp/automate#7]
Hi,

What not to use [deployer](https://deployer.org/)? 😃

**Comment by julienj** [comment]
Hello Anton

I used your project many times for projects and appreciated it.
He was a model for the creation of Automate.

But I also think the deployment can be very simple: just an order list of command line (no PHP, juste YAML)
Here is the idea of Automate and the reason for this new project :)

**Comment by antonmedv** [comment]
Nice, I'm working on yaml support as well.
